# Generated by Django 5.1.7 on 2025-09-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.CharField(max_length=64)),
                ('dst_ip', models.CharField(max_length=64)),
                ('protocol', models.CharField(max_length=16)),
                ('severity', models.CharField(default='low', max_length=8)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='monitoring__created_13e6e7_idx'), models.Index(fields=['protocol'], name='monitoring__protoco_62b9b9_idx'), models.Index(fields=['severity'], name='monitoring__severit_b464a0_idx')],
            },
        ),
    ]
